import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, LogIn, LogOut, Package, Plus, RefreshCw, Save, Settings, ShoppingBag, Trash2, X } from "lucide-react";
import toast from "react-hot-toast";
import { useLanguage } from "../context/LanguageContext";
import { archiveManagerProduct, createManagerProduct, getManagerCategories, getManagerProducts, getManagerRecentOrders, getManagerSession, getManagerStoreData, managerLogin, managerLogout, updateManagerProduct, updateManagerStoreContent, updateManagerStoreSetting } from "../services/managerApi";
import { createEmptyProductExtraField, parseProductDescription, serializeProductDescription } from "../utils/productExtraFields";

const EMPTY={sku:"",name:"",description:"",price:"",oldPrice:"",initialStock:0,reorderLevel:0,categoryId:"",color:"",material:"",size:"",extraFields:[],images:[],publish:true,featured:false,isNew:false,isSale:false};
const input="h-11 w-full rounded-xl border border-[#dfe5dc] bg-white px-3 text-sm font-semibold outline-none focus:border-[#B4C4AD] focus:ring-4 focus:ring-[#EFE8E2]";
const area=`${input} min-h-28 py-3`;
const newSku=()=>`OPT-${Date.now().toString().slice(-7)}`;

function Manager(){
  const {t,isEnglish}=useLanguage();
  const [session,setSession]=useState(()=>getManagerSession());
  const [login,setLogin]=useState({email:"",password:""});
  const [tab,setTab]=useState("products");
  const [data,setData]=useState({products:[],categories:[],orders:[],store:{settings:{},content:{}}});
  const [form,setForm]=useState(EMPTY); const [editing,setEditing]=useState(null); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false);
  const set=(k,v)=>setForm(f=>({...f,[k]:v}));
  const load=useCallback(async()=>{if(!session)return;setLoading(true);try{const [products,categories,orders,store]=await Promise.all([getManagerProducts(),getManagerCategories(),getManagerRecentOrders("all"),getManagerStoreData()]);setData({products,categories,orders,store:store||{settings:{},content:{}}});}catch(e){if(e?.status===401)setSession(null);toast.error(e?.message||t("تعذر تحميل بيانات الإدارة"));}finally{setLoading(false);}},[session,t]);
  useEffect(()=>{load();},[load]);
  const filtered=useMemo(()=>data.products.filter(p=>p.status!=="ARCHIVED"&&(!query.trim()||[p.name,p.sku,p.category?.name].some(v=>String(v||"").toLowerCase().includes(query.trim().toLowerCase())))),[data.products,query]);
  const edit=p=>{const parsed=parseProductDescription(p.description);setEditing(p);setForm({...EMPTY,sku:p.sku||newSku(),name:p.name||"",description:parsed.description,price:p.price??"",oldPrice:p.oldPrice??"",initialStock:p.stock??0,reorderLevel:p.reorderLevel??0,categoryId:p.categoryId||"",color:p.color||"",material:p.material||"",size:p.size||"",extraFields:parsed.extraFields,images:Array.isArray(p.images)?p.images.map(x=>typeof x==="string"?x:x?.url).filter(Boolean):[],publish:p.status==="PUBLISHED"&&p.showOnStore!==false,featured:p.featured===true,isNew:p.isNew===true,isSale:p.isSale===true});setTab("products");};
  const reset=()=>{setEditing(null);setForm({...EMPTY,sku:newSku()});};
  const save=async e=>{e.preventDefault();if(!form.name.trim())return toast.error(t("اكتب اسم المنتج."));if(!(Number(form.price)>0))return toast.error(t("أدخل سعرًا صحيحًا."));setSaving(true);try{const payload={...form,description:serializeProductDescription(form.description,form.extraFields),extraFields:undefined};const saved=editing?await updateManagerProduct(editing.id,payload):await createManagerProduct(payload);setData(d=>({...d,products:editing?d.products.map(p=>p.id===editing.id?saved:p):[saved,...d.products]}));reset();toast.success(t("تم حفظ المنتج"));}catch(e2){toast.error(e2?.message||t("تعذر حفظ المنتج"));}finally{setSaving(false);}};
  const remove=async id=>{if(!confirm(t("أرشفة المنتج؟")))return;try{await archiveManagerProduct(id);setData(d=>({...d,products:d.products.filter(p=>p.id!==id)}));}catch(e){toast.error(e?.message||t("تعذر الأرشفة"));}};
  const loginSubmit=async e=>{e.preventDefault();setLoading(true);try{await managerLogin(login.email,login.password);setSession(getManagerSession());}catch(e2){toast.error(e2?.message||t("بيانات الدخول غير صحيحة"));}finally{setLoading(false);}};
  if(!session)return <main className="min-h-screen bg-[#EFE8E2] px-4 py-16"><form onSubmit={loginSubmit} className="mx-auto max-w-md rounded-[28px] border border-[#dfe6dc] bg-white p-7 shadow-sm"><p className="text-xs font-black text-[#657361]">OPTICANA</p><h1 className="mt-2 text-3xl font-black">{t("إدارة المتجر")}</h1><div className="mt-7 space-y-4"><div><label className="mb-2 block text-xs font-black">{t("البريد الإلكتروني")} *</label><input className={input} type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} required/></div><div><label className="mb-2 block text-xs font-black">{t("كلمة المرور")} *</label><input className={input} type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required/></div><button disabled={loading} className="inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#B4C4AD] text-sm font-black text-white"><LogIn size={16}/>{loading?t("جاري الدخول..."):t("دخول")}</button></div></form></main>;
  const business=data.store.settings?.business||{}; const general=data.store.settings?.general||{}; const hero=data.store.content?.home?.hero||{};
  return <main className="min-h-screen bg-[#EFE8E2] px-4 py-6 sm:px-6"><div className="mx-auto max-w-7xl">
    <header className="mb-5 flex flex-col gap-3 rounded-[26px] border border-[#dfe6dc] bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black text-[#657361]">OPTICANA</p><h1 className="mt-1 text-3xl font-black">{t("إدارة المتجر")}</h1><p className="text-xs text-[#818b80]">{session.user?.email||""}</p></div><div className="flex gap-2"><button onClick={load} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#dfe5dc] px-3 text-xs font-black"><RefreshCw size={14}/>{t("تحديث")}</button><button onClick={()=>{managerLogout();setSession(null);}} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#eadfdb] px-3 text-xs font-black text-[#8a655b]"><LogOut size={14}/>{t("خروج")}</button></div></header>
    <nav className="mb-5 flex flex-wrap gap-2 rounded-2xl border border-[#dfe6dc] bg-white p-2 shadow-sm">{[["products",Package,t("المنتجات")],["orders",ShoppingBag,t("الطلبات")],["settings",Settings,t("الإعدادات")]].map(([id,I,text])=><button key={id} onClick={()=>setTab(id)} className={`inline-flex h-10 items-center gap-2 rounded-xl px-4 text-xs font-black ${tab===id?"bg-[#B4C4AD] text-white":"text-[#667360] hover:bg-[#f4f7f2]"}`}><I size={15}/>{text}</button>)}</nav>
    {loading&&<div className="mb-4 rounded-xl border border-[#dfe6dc] bg-white p-3 text-center text-xs font-black">{t("جاري التحميل...")}</div>}
    {tab==="products"&&<div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
      <form onSubmit={save} className="rounded-[26px] border border-[#dfe6dc] bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-black">{editing?t("تعديل المنتج"):t("إضافة منتج")}</h2><p className="mt-1 text-xs text-[#7d877b]">{t("أضف حقولًا مخصصة مثل نوع العدسة")}</p></div>{editing&&<button type="button" onClick={reset} className="rounded-xl border px-3 py-2 text-xs font-black"><X size={14}/></button>}</div><div className="grid gap-3 sm:grid-cols-2"><Field label={t("اسم المنتج")} required><input className={input} value={form.name} onChange={e=>set("name",e.target.value)} required/></Field><Field label="SKU"><input className={input} value={form.sku} onChange={e=>set("sku",e.target.value)}/></Field><Field label={t("السعر")} required><input className={input} type="number" min="0" step="0.01" value={form.price} onChange={e=>set("price",e.target.value)} required/></Field><Field label={t("السعر القديم")}><input className={input} type="number" min="0" step="0.01" value={form.oldPrice} onChange={e=>set("oldPrice",e.target.value)}/></Field><Field label={t("المخزون")}><input className={input} type="number" min="0" value={form.initialStock} onChange={e=>set("initialStock",e.target.value)}/></Field><Field label={t("التصنيف")}><select className={input} value={form.categoryId} onChange={e=>set("categoryId",e.target.value)}><option value="">{t("بدون تصنيف")}</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label={t("المادة")}><input className={input} value={form.material} onChange={e=>set("material",e.target.value)}/></Field><Field label={t("المقاس")}><input className={input} value={form.size} onChange={e=>set("size",e.target.value)}/></Field></div><div className="mt-3"><Field label={t("الوصف")}><textarea className={area} value={form.description} onChange={e=>set("description",e.target.value)}/></Field></div>
        <div className="mt-4 rounded-2xl border border-[#e2e8df] bg-[#f8faf7] p-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-black">{t("الحقول الإضافية")}</h3><p className="mt-1 text-xs text-[#818b80]">{t("مثال: نوع العدسة = مضادة للانعكاس")}</p></div><button type="button" onClick={()=>set("extraFields",[...form.extraFields,createEmptyProductExtraField(form.extraFields.length)])} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#B4C4AD] px-3 text-xs font-black text-white"><Plus size={14}/>{t("إضافة حقل")}</button></div><div className="mt-3 space-y-2">{form.extraFields.map((f,i)=><div key={f.id} className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input className={input} placeholder={t("اسم الحقل")} value={f.label} onChange={e=>set("extraFields",form.extraFields.map((x,n)=>n===i?{...x,label:e.target.value}:x))}/><input className={input} placeholder={t("قيمة الحقل")} value={f.value} onChange={e=>set("extraFields",form.extraFields.map((x,n)=>n===i?{...x,value:e.target.value}:x))}/><button type="button" onClick={()=>set("extraFields",form.extraFields.filter((_,n)=>n!==i))} className="rounded-xl border border-[#eadfdb] px-3 text-[#8a655b]"><Trash2 size={14}/></button></div>)}</div></div>
        <div className="mt-4 flex flex-wrap gap-2">{[["publish",t("نشر")],["featured",t("مميز")],["isNew",t("جديد")],["isSale",t("عرض")]].map(([k,txt])=><button key={k} type="button" onClick={()=>set(k,!form[k])} className={`inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-black ${form[k]?"bg-[#f1f5ee]":"bg-white"}`}><span className={`flex h-5 w-5 items-center justify-center rounded-md border ${form[k]?"bg-[#657361] text-white":"text-transparent"}`}><Check size={12}/></span>{txt}</button>)}</div><button disabled={saving} className="mt-4 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#B4C4AD] text-sm font-black text-white"><Save size={16}/>{saving?t("جاري الحفظ..."):t("حفظ المنتج")}</button>
      </form>
      <section className="rounded-[26px] border border-[#dfe6dc] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">{t("المنتجات")}</h2><p className="mt-1 text-xs text-[#818b80]">{filtered.length} {t("منتج")}</p></div><button onClick={reset} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#B4C4AD] px-3 text-xs font-black text-white"><Plus size={14}/>{t("إضافة")}</button></div><input className={`${input} mt-3`} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("بحث")}/><div className="mt-3 space-y-2">{filtered.map(p=><article key={p.id} className="rounded-2xl border border-[#e2e8df] p-3"><div className="flex items-center justify-between gap-3"><div><p className="font-black">{p.name}</p><p className="mt-1 text-[11px] text-[#818b80]">{p.sku} · {Number(p.price||0).toLocaleString(isEnglish?"en-EG":"ar-EG")} ج.م</p><p className="mt-1 text-[11px] text-[#818b80]">{p.status} · {p.stock||0}</p></div><div className="flex gap-1"><button onClick={()=>edit(p)} className="rounded-lg border px-2 py-1 text-[11px] font-black">{t("تعديل")}</button><button onClick={()=>remove(p.id)} className="rounded-lg border border-[#eadfdb] px-2 py-1 text-[#8a655b]"><Trash2 size={13}/></button></div></div></article>)}</div></section>
    </div>}
    {tab==="orders"&&<section className="rounded-[26px] border border-[#dfe6dc] bg-white shadow-sm"><div className="border-b border-[#EFE8E2] p-5"><h2 className="text-xl font-black">{t("الطلبات")}</h2></div><div className="divide-y divide-[#EFE8E2]">{data.orders.map(o=>{const raw=String(o.customer?.whatsapp||o.customer?.phone||"").trim();const digits=raw.replace(/\D/g,"").replace(/^00/,"");const done=o.status==="COMPLETED";return <article key={o.id} className={`p-5 ${done?"bg-[#f2f6ef]":"bg-white"}`}><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-black">{o.orderNumber} <span className="ms-2 rounded-full border px-2 py-1 text-[10px] font-black">{o.status}</span></p><p className="mt-2 text-sm font-bold">{o.customer?.name||t("عميل")}</p><p className="mt-1 text-xs text-[#73806f]">{t("واتساب")}: {raw||t("غير متوفر")}</p></div>{digits?<a href={`https://wa.me/${digits}`} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center justify-center rounded-xl bg-[#B4C4AD] px-3 text-xs font-black text-white">{t("فتح في واتساب")}</a>:<span className="inline-flex h-10 items-center rounded-xl border px-3 text-xs font-black">{t("غير متوفر")}</span>}</div></article>})}{!data.orders.length&&<div className="p-12 text-center text-xs text-[#818b80]">{t("لا توجد طلبات")}</div>}</div></section>}
    {tab==="settings"&&<div className="grid gap-5 lg:grid-cols-2"><section className="rounded-[26px] border border-[#dfe6dc] bg-white p-5 shadow-sm"><h2 className="text-xl font-black">{t("إعدادات المتجر")}</h2><div className="mt-4 space-y-3"><Field label={t("اسم المتجر")}><input className={input} value={business.storeName||""} onChange={e=>setData(d=>({...d,store:{...d.store,settings:{...d.store.settings,business:{...business,storeName:e.target.value}}}})}/></Field><Field label={t("واتساب المتجر")}><input className={input} value={business.whatsapp||""} onChange={e=>setData(d=>({...d,store:{...d.store,settings:{...d.store.settings,business:{...business,whatsapp:e.target.value}}}})}/></Field><Field label={t("الشعار")}><input className={input} value={general.slogan||""} onChange={e=>setData(d=>({...d,store:{...d.store,settings:{...d.store.settings,general:{...general,slogan:e.target.value}}}})}/></Field><button disabled={saving} onClick={async()=>{setSaving(true);try{await updateManagerStoreSetting("business",data.store.settings.business);await updateManagerStoreSetting("general",data.store.settings.general);toast.success(t("تم الحفظ"));}catch(e){toast.error(e?.message||t("تعذر الحفظ"));}finally{setSaving(false);}}} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#B4C4AD] px-4 text-xs font-black text-white"><Save size={15}/>{t("حفظ")}</button></div></section><section className="rounded-[26px] border border-[#dfe6dc] bg-white p-5 shadow-sm"><h2 className="text-xl font-black">{t("Hero")}</h2><p className="mt-2 break-all text-xs text-[#778174]">{hero.image||t("لا توجد صورة")}</p><button onClick={async()=>{try{await updateManagerStoreContent("home",data.store.content.home||{});toast.success(t("تم حفظ CMS"));}catch(e){toast.error(e?.message||t("تعذر الحفظ"));}}} className="mt-4 inline-flex h-11 items-center gap-2 rounded-xl bg-[#B4C4AD] px-4 text-xs font-black text-white"><Save size={15}/>{t("حفظ CMS")}</button></section></div>}
  </div></main>;
}
function Field({label,required,children}){return <label className="block"><span className="mb-2 block text-xs font-black text-[#5d685a]">{label}{required?" *":""}</span>{children}</label>}
export default Manager;
